using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Emissary.SourceGenerators;

/// <summary>Emits the generated partial-type source for one [ClaudeSchema] type.</summary>
internal static class SchemaEmitter
{
    public static string Emit(SchemaModel model)
    {
        string schema = SchemaJson.BuildObject(
            model.Pocos,
            model.Pocos[model.RootIndex].Members,
            strict: true,
            model.RootDescription);

        var builder = new StringBuilder(1024);
        builder.AppendLine("// <auto-generated by Emissary.SourceGenerators />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable");

        int braceDepth = 0;
        if (model.Namespace is not null)
        {
            builder.Append("namespace ").AppendLine(model.Namespace);
            builder.AppendLine("{");
            braceDepth++;
        }

        for (int i = 0; i < model.Containers.Count; i++)
        {
            builder.Append("partial ").Append(model.Containers[i]);
            if (i == model.Containers.Count - 1)
            {
                // The schema type itself also implements IClaudeSchema for generic access.
                builder.Append(" : global::Emissary.IClaudeSchema");
            }

            builder.AppendLine();
            builder.AppendLine("{");
            braceDepth++;
        }

        builder.AppendLine("/// <summary>The strict JSON Schema for this type, generated at compile time.</summary>");
        builder.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"Emissary.SourceGenerators\", \"{GeneratorInfo.Version}\")]");
        builder.Append("public static string JsonSchema { get; } = ")
            .Append(SymbolDisplay.FormatLiteral(schema, quote: true)).AppendLine(";");

        for (; braceDepth > 0; braceDepth--)
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }
}
