using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Emissary.SourceGenerators;

/// <summary>Emits the generated partial-type source for one analyzed tool method.</summary>
internal static class ToolEmitter
{
    private const string GeneratorVersion = "0.1.0";

    public static string Emit(ToolModel model)
    {
        var builder = new StringBuilder(4096);
        builder.AppendLine("// <auto-generated by Emissary.SourceGenerators />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable");

        int braceDepth = 0;
        if (model.Namespace is not null)
        {
            builder.Append("namespace ").AppendLine(model.Namespace);
            builder.AppendLine("{");
            braceDepth++;
        }

        foreach (string container in model.Containers)
        {
            builder.Append("partial ").AppendLine(container);
            builder.AppendLine("{");
            braceDepth++;
        }

        EmitToolProperty(builder, model);
        EmitDispatcher(builder, model);

        for (; braceDepth > 0; braceDepth--)
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void EmitToolProperty(StringBuilder builder, ToolModel model)
    {
        builder.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"Emissary.SourceGenerators\", \"{GeneratorVersion}\")]");
        builder.AppendLine($"public static global::Emissary.ToolDefinition {model.MethodName}Tool {{ get; }} = new global::Emissary.ToolDefinition(");
        builder.Append("    ").Append(Literal(model.ToolName)).AppendLine(",");
        builder.Append("    ").Append(Literal(model.Description)).AppendLine(",");
        builder.Append("    ").Append(Literal(BuildSchema(model))).AppendLine(",");
        builder.Append("    __EmissaryInvoke_").Append(model.MethodName).AppendLine(",");
        builder.Append("    ").Append(model.RequiredPolicy is null ? "null" : Literal(model.RequiredPolicy)).AppendLine(",");
        builder.Append("    ").Append(model.Untrusted ? "true" : "false").AppendLine(",");
        builder.Append("    ").Append(model.Privileged ? "true" : "false").AppendLine(");");
        builder.AppendLine();
    }

    private static void EmitDispatcher(StringBuilder builder, ToolModel model)
    {
        builder.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"Emissary.SourceGenerators\", \"{GeneratorVersion}\")]");
        string asyncModifier = model.IsAsync ? "async " : "";
        builder.AppendLine($"private static {asyncModifier}global::System.Threading.Tasks.ValueTask<string> __EmissaryInvoke_{model.MethodName}(global::System.Text.Json.JsonElement input, global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine("{");

        foreach (var parameter in model.Parameters)
        {
            if (!parameter.IsCancellationToken)
            {
                EmitBinder(builder, model, parameter);
            }
        }

        string arguments = string.Join(", ", model.Parameters.Select(
            p => p.IsCancellationToken ? "cancellationToken" : "__arg_" + p.CSharpName));

        if (model.IsAsync)
        {
            builder.AppendLine($"    var __result = await {model.MethodName}({arguments}).ConfigureAwait(false);");
            builder.Append("    return ").Append(ReturnConversion(model.ReturnKind)).AppendLine(";");
        }
        else
        {
            builder.AppendLine($"    var __result = {model.MethodName}({arguments});");
            builder.Append("    return new global::System.Threading.Tasks.ValueTask<string>(")
                .Append(ReturnConversion(model.ReturnKind)).AppendLine(");");
        }

        EmitLocalFunctions(builder, model);
        builder.AppendLine("}");
    }

    private static void EmitBinder(StringBuilder builder, ToolModel model, ParameterModel parameter)
    {
        string element = "__p_" + parameter.CSharpName;
        string fallback = parameter.IsOptional
            ? parameter.DefaultLiteral
            : $"throw new global::Emissary.ToolArgumentException({Literal($"Tool '{model.ToolName}' is missing required argument '{parameter.JsonName}'.")})";

        builder.AppendLine(
            $"    {parameter.DeclaredTypeFullName} __arg_{parameter.CSharpName} = " +
            $"input.TryGetProperty({Literal(parameter.JsonName)}, out global::System.Text.Json.JsonElement {element}) " +
            $"&& {element}.ValueKind != global::System.Text.Json.JsonValueKind.Null " +
            $"? {Reader(model, parameter, element)} : {fallback};");
    }

    private static string Reader(ToolModel model, ParameterModel parameter, string element) => parameter.Kind switch
    {
        JsonKind.Enum => EnumParserName(parameter.EnumType!) + "(" + element + ".GetString()!)",
        JsonKind.Object => model.Pocos[parameter.PocoIndex].BinderName + "(" + element + ")",
        JsonKind.Array => ArrayReaderName(parameter.ElementKind) + "(" + element + ")",
        _ => PrimitiveReader(parameter.Kind, element),
    };

    private static string PrimitiveReader(JsonKind kind, string element) => kind switch
    {
        JsonKind.String => element + ".GetString()!",
        JsonKind.Bool => element + ".GetBoolean()",
        JsonKind.Int => element + ".GetInt32()",
        JsonKind.Long => element + ".GetInt64()",
        _ => element + ".GetDouble()",
    };

    private static string ReturnConversion(JsonKind kind) => kind switch
    {
        JsonKind.String => "__result ?? string.Empty",
        JsonKind.Bool => "__result ? \"true\" : \"false\"",
        JsonKind.Int or JsonKind.Long => "__result.ToString(global::System.Globalization.CultureInfo.InvariantCulture)",
        JsonKind.Double => "__result.ToString(\"R\", global::System.Globalization.CultureInfo.InvariantCulture)",
        _ => "__result.ToString()",
    };

    private static void EmitLocalFunctions(StringBuilder builder, ToolModel model)
    {
        var emittedEnums = new HashSet<string>();
        var emittedArrayKinds = new HashSet<JsonKind>();

        foreach (var binding in AllBindings(model))
        {
            if (binding.Kind == JsonKind.Enum && emittedEnums.Add(EnumParserName(binding.EnumType!)))
            {
                EmitEnumParser(builder, binding.EnumType!);
            }
            else if (binding.Kind == JsonKind.Array && emittedArrayKinds.Add(binding.ElementKind))
            {
                EmitArrayReader(builder, binding.ElementKind);
            }
        }

        foreach (var poco in model.Pocos)
        {
            EmitPocoBinder(builder, model, poco);
        }
    }

    private static IEnumerable<ParameterModel> AllBindings(ToolModel model)
    {
        foreach (var parameter in model.Parameters)
        {
            if (!parameter.IsCancellationToken)
            {
                yield return parameter;
            }
        }

        foreach (var poco in model.Pocos)
        {
            foreach (var member in poco.Members)
            {
                yield return member;
            }
        }
    }

    private static void EmitPocoBinder(StringBuilder builder, ToolModel model, PocoModel poco)
    {
        builder.AppendLine($"    static {poco.FullName} {poco.BinderName}(global::System.Text.Json.JsonElement element)");
        builder.AppendLine("    {");

        foreach (var member in poco.Members)
        {
            string element = "__e_" + member.CSharpName;
            string fallback = member.IsOptional
                ? member.DefaultLiteral
                : $"throw new global::Emissary.ToolArgumentException({Literal($"Object '{TrimGlobal(poco.FullName)}' is missing required member '{member.JsonName}'.")})";

            builder.AppendLine(
                $"        {member.DeclaredTypeFullName} __v_{member.CSharpName} = " +
                $"element.TryGetProperty({Literal(member.JsonName)}, out global::System.Text.Json.JsonElement {element}) " +
                $"&& {element}.ValueKind != global::System.Text.Json.JsonValueKind.Null " +
                $"? {Reader(model, member, element)} : {fallback};");
        }

        builder.AppendLine(poco.UsesConstructor
            ? $"        return new {poco.FullName}({string.Join(", ", poco.Members.Select(m => "__v_" + m.CSharpName))});"
            : $"        return new {poco.FullName} {{ {string.Join(", ", poco.Members.Select(m => m.CSharpName + " = __v_" + m.CSharpName))} }};");
        builder.AppendLine("    }");
    }

    private static void EmitEnumParser(StringBuilder builder, INamedTypeSymbol enumType)
    {
        string fullName = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        builder.AppendLine($"    static {fullName} {EnumParserName(enumType)}(string value) => value switch");
        builder.AppendLine("    {");
        foreach (string member in SchemaJson.EnumMemberNames(enumType))
        {
            builder.AppendLine($"        {Literal(member)} => {fullName}.{member},");
        }

        string message = $"Unknown value '{{0}}' for '{enumType.ToDisplayString()}'.";
        builder.AppendLine($"        _ => throw new global::Emissary.ToolArgumentException(string.Format(global::System.Globalization.CultureInfo.InvariantCulture, {Literal(message)}, value)),");
        builder.AppendLine("    };");
    }

    private static void EmitArrayReader(StringBuilder builder, JsonKind elementKind)
    {
        string elementType = ElementTypeName(elementKind);
        builder.AppendLine($"    static {elementType}[] {ArrayReaderName(elementKind)}(global::System.Text.Json.JsonElement element)");
        builder.AppendLine("    {");
        builder.AppendLine($"        var list = new global::System.Collections.Generic.List<{elementType}>();");
        builder.AppendLine("        foreach (var item in element.EnumerateArray())");
        builder.AppendLine("        {");
        builder.AppendLine($"            list.Add({PrimitiveReader(elementKind, "item")});");
        builder.AppendLine("        }");
        builder.AppendLine("        return list.ToArray();");
        builder.AppendLine("    }");
    }

    internal static string BuildSchema(ToolModel model) =>
        SchemaJson.BuildObject(
            model.Pocos,
            model.Parameters.Where(p => !p.IsCancellationToken),
            strict: false,
            rootDescription: null);

    private static string ElementTypeName(JsonKind kind) => kind switch
    {
        JsonKind.String => "string",
        JsonKind.Bool => "bool",
        JsonKind.Int => "int",
        JsonKind.Long => "long",
        _ => "double",
    };

    private static string EnumParserName(INamedTypeSymbol enumType) =>
        "__EmissaryParse_" + NameHelpers.ToIdentifier(enumType.ToDisplayString());

    private static string ArrayReaderName(JsonKind elementKind) =>
        "__EmissaryReadArray_" + elementKind;

    // FullName always comes from SymbolDisplayFormat.FullyQualifiedFormat, so the
    // "global::" prefix is guaranteed.
    private static string TrimGlobal(string fullName) => fullName.Substring(8);

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
}
