<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <!-- CA1822: BenchmarkDotNet requires instance benchmark methods. -->
    <NoWarn>$(NoWarn);CA1822</NoWarn>
  </PropertyGroup>

</Project>
